import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { ArrowLeft, Server, Layers, Cloud, CheckCircle2, AlertCircle, Loader2 } from "lucide-react";
import InputBox from "../components/InputBox";

// Read-only wrapper for InputBox
export default function SharePage() {
  const { id } = useParams();
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchSharedStack = async () => {
      try {
        const res = await fetch(`http://127.0.0.1:8000/share/${id}`);
        
        if (!res.ok) {
          if (res.status === 404) {
            throw new Error("Shared stack not found");
          }
          throw new Error("Failed to load shared stack");
        }

        const data = await res.json();
        setResult(data.data);
      } catch (err) {
        console.error("Error fetching shared stack:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchSharedStack();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0B0F19] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 text-cyan-400 animate-spin mx-auto mb-4" />
          <p className="text-gray-400">Loading shared tech stack...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#0B0F19] flex items-center justify-center">
        <div className="text-center max-w-md px-6">
          <AlertCircle className="w-16 h-16 text-red-400 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-white mb-2">Stack Not Found</h2>
          <p className="text-gray-400 mb-6">{error}</p>
          <Link
            to="/"
            className="inline-flex items-center gap-2 px-6 py-3 bg-cyan-500 hover:bg-cyan-600 text-white rounded-lg font-medium transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Go Home
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0B0F19]">
      {/* Header */}
      <header className="border-b border-gray-800 bg-[#111827]">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Server className="w-6 h-6 text-cyan-400" />
            <span className="font-bold text-white text-lg">StackMind</span>
            <span className="text-gray-500">|</span>
            <span className="text-gray-400">Shared Stack</span>
          </div>
          <Link
            to="/dashboard"
            className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Create Your Own</span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-6xl mx-auto px-6 py-8">
        <div className="mb-6">
          <div className="flex items-center gap-3 text-emerald-400 mb-2">
            <CheckCircle2 className="w-6 h-6" />
            <span className="font-semibold text-lg">Shared Tech Stack</span>
          </div>
          <p className="text-gray-400 text-sm">
            This tech stack was shared with you. View the complete architecture and technology recommendations below.
          </p>
        </div>

        {/* Reuse InputBox in read-only mode by passing result */}
        <InputBox input="" setInput={() => {}} result={result} setResult={() => {}} />
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 bg-[#111827] mt-12">
        <div className="max-w-6xl mx-auto px-6 py-6 text-center text-gray-500 text-sm">
          <p>Generated by StackMind • AI-Powered Tech Stack Recommender</p>
        </div>
      </footer>
    </div>
  );
}
